version: '3.8'

services:
  npm-registry:
    image: verdaccio/verdaccio
    container_name: "npm-registry"
    restart: always
    networks:
      - npm-registry-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./config:/verdaccio/conf"
      - "./plugins:/verdaccio/plugins"

networks:
  npm-registry-network:
